### ISSUE TITLE
TypeScript 7: typescript.findConfigFile is not a function

### ISSUE THREAD

**Issue by tpluscode** [cosmiconfig/cosmiconfig#363]
When I upgraded TS to v7.0.2, cosmiconfig fails with error

```
typescript.findConfigFile is not a function
```

**Comment by d-fischer** [comment]
TypeScript version 7 is incompatible with *all* packages that use its API, since it was not implemented at all.

However, the next major version of cosmiconfig will depend on Node's native TS loading rather than the `typescript` package, eliminating this shortcoming. See also #350 - in case you want to use it today, the alpha version should be fine.

As such, this is a duplicate to #350.
